---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
ustreasuries      
===============   

*ustreasuries* is an R-language package which downloads daily Constant-Maturity Treasury (CMT) yields from 1962 to the most-recently completed business day and provides visualizations & analytics that use that data (all the 'greeks' for derivative analysis will be included in the next release).   

Historical data from 1962 to 2015 was sourced from the Federal Reserve's H15 dataset; data from 2016 onward is pulled in real time from an XML feed provided by the US Treasury Department.

### Vignettes

* **cmt-rates** a description of Constant Maturity 
and Annualized Percentage rates
* **yield-curves** examples of downloading the data and printing yield curves
for interesting periods in recent financial history
* **plot-10year** a plot of the 10-year from 1962 to present

### Functions

* **USTreasuryRates** downloads a data.frame with daily data from 1962
* **PrintYieldCurves** prints one or more yield curves
* **APY** converts Constant-Maturity Treasury (CMT) yields to Annualized 
Percentage Yields (APY)

## Installation

We're not on CRAN yet; get the development version from GitHub:

```R
# see https://github.com/hadley/devtools for the
# best procedure to install *devtools* on your
# system; Windows in particular has somewhat
# complicated requirements

devtools::install_github("grfiv/treasuries")

# Notes: 
#    1. Add 'build_vignettes=TRUE' to include vignettes 
#       (recommended, but a current version of pandoc is required)
#    2. add 'auth_token="..."' if you get a 404
#       contact the author for this
#    3. if you receive a message about corrupt databases or fetch(key), 
#       restarting R will fix the problem;
#       these appear to be issues with devtools 1.10.0.9000
```
